//! the below url is generated by render.com 
//! url changes on every build/Deploy 

const apiURL = "https://mern-chat-backend-0koj.onrender.com";

export default apiURL;


/*
https://mern-chat-backend-0koj.onrender.com

--> renders the following:
{
  "project": "MERN Chat App using Socket.IO",
  "message": "Welcome to MERN Chat Application",
  "developedBy": "MasynTech",
  "website": "www.masynctech.com"
}
*/

